MultiMC/MultiMC5-translate

README.md, zh.po
Translate the MultiMC into Chinese.
some bug in it. see picture for detail.
@peterix
=> Added Chinese translation

zh.po
=> Fixed wrong translate

zh.po
=> Update Chinese Translate to 0.7.11.

de.po
=> A few translations

de.po
Non-formal
Added missing translations
=> Translations

zh.po
Fix some typo.
Signed-by: Charlie Jiang<cqjjjzr@126.com>
=> Update Chinese Translate.

it.po
=> Updated IT translation

zh.po
=> Update Chinese translation. Fix bunch of bugs.

fr.po
Apply changes from #2127 to translations file
(https://github.com/MultiMC/MultiMC5/issues/2127)
=> Fix translations (issure #2127)

zh_TW.po
=> Update Chinese(Taiwan) translation and fix several bugs

zh_TW.po
=> Update Chinese(Taiwan) translations

zh.po
=> Fix a typo

pl.po
I managed to translate quite a bit of code to Polish. I reached 87% translated.
There's still some fuzzy stuff here and there, but it's stuff I'm not entire sure of. However I managed to fix most of the previous fuzzy stuff (lotta translations were simply incorrect).
There was a couple fuzzy translations that were totally incorrect, but I wasn't really sure how to translate it properly; I decided to just straight up remove the translation, because it's better to have some correct English text than incorrect Polish text. (I hope you get what I mean =P)
Don't hesitate asking about stuff, I'll gladly help as much as I can. =)
=> pl.po translation

es.po
From `@Father Gentlespie#1917` on Discord.
=> Update ES translation

de.po
For the most part, it looked like a 6-year-old translated it.
=> Update German translation

pt_BR.po
These Strings are the right ones.
=> New strings.

et.po
Main menu & settings mostly translated to Estonian. Translated 525 of 850 (61%)
=> Added Estonian translation

zh.po
=> fix zh fabric and some update

et.po
86% translated, translated some new strings.
=> Translated and fixed some Estonian strings.

hu.po
+ Added a few new translations for strings that were left empty in Hungarian.
+ Fixed a few broken translations
+ Replaced a few incorrect translations
+ Replaced a few words that didn't need translating  ( example: Mod, URL )
=> Fixed a few fields and new translations

ko.po
As is.
btw, I found typo in original string, so opened an issue.
=> Ko translate update

pt_PT.po
translation in european portuguese for multimc
=> New portuguese (portugal) translation

nn.po
Dear developers,
I've created a new translation for Norwegian(nynorsk), lang code `nn_NO` or `nn`.
So far the following was done:
- Created new nn.po from POT-template
- Translated the visible and static strings in the UI.
=> New translation for Norwegian(nynorsk)
